[variables]
NIXPACKS_PYTHON_VERSION = "3.11"
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
dependsOn = ["install"]

[phases.install]
cmds = [
    "apt-get update && apt-get install -y curl",
    "pip install -r requirements.txt",
    "npm install"
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "python main.py"